import java.util.HashMap;
import java.util.Map;

/*
222098856 Salafia Ndeshikeya
223063495 Barthromew M Mufaya Junior
223003344 Martha Haihambo
223053147 Fidelity Friedriech
223010391 Ndatungeumbo Dumeni
222115823 Nicola Basson
222129433 Shalom Birech
220088047 Joshua Muulike
Stacy T Muheua 223063215
 */
//SRT Scheduling algorithm
class Records {
    int rowNumber;
    String fullName;
    int age;
    String country;
    String city;
    String status;

    public Records(int rowNumber, String fullName, int age, String country, String city, String status) {
        this.rowNumber = rowNumber;
        this.fullName = fullName;
        this.age = age;
        this.country = country;
        this.city = city;
        this.status = status;
    }
}

class Process {
    String fileName;
    int cpuCycle;
    int arrivalTime;

    public Process(String fileName, int cpuCycle, int art)
    {
        this.fileName = fileName;
        this.cpuCycle = cpuCycle;
        this.arrivalTime = art;
    }
}


public class Main {

    static void Computation(Records[] records) {

        double sumAge = 0;
        int minAge = Integer.MAX_VALUE;
        int maxAge = Integer.MIN_VALUE;
        Map<String, Integer> statusCount = new HashMap<>();

        for (Records record : records) {
            sumAge += record.age;
            minAge = Math.min(minAge, record.age);
            maxAge = Math.max(maxAge, record.age);


            statusCount.put(record.status, statusCount.getOrDefault(record.status, 0) + 1);
        }
        double avgAge = sumAge / records.length;


        System.out.println("Average age: " + avgAge);
        System.out.println("Minimum age: " + minAge);
        System.out.println("Maximum age: " + maxAge);
        System.out.println("Patients count per patient status:");
        for (Map.Entry<String, Integer> entry : statusCount.entrySet()) {
            System.out.println(entry.getKey() + ": " + entry.getValue());
        }
        System.out.println();
    }
    static void WaitingTime(Process[] proc, int n, int[] wt) {
        int[] rt = new int[n];

        for (int i = 0; i < n; i++)
            rt[i] = proc[i].cpuCycle;

        int complete = 0, time = 0, minm = Integer.MAX_VALUE;
        int shortest = 0, finish_time;
        boolean check = false;

        while (complete != n) {
            for (int j = 0; j < n; j++) {
                if ((proc[j].arrivalTime <= time) && (rt[j] < minm) && rt[j] > 0) {
                    minm = rt[j];
                    shortest = j;
                    check = true;
                }
            }
            if (!check) {
                time++;
                continue;
            }
            rt[shortest]--;
            minm = rt[shortest];
            if (minm == 0) minm = Integer.MAX_VALUE;
            if (rt[shortest] == 0) {
                complete++;
                check = false;
                finish_time = time + 1;
                wt[shortest] = finish_time - proc[shortest].cpuCycle - proc[shortest].arrivalTime;
                if (wt[shortest] < 0)
                    wt[shortest] = 0;
            }
            time++;
        }
    }

    static void TurnAroundTime(Process[] proc,int n,int[] wt, int[] tat)
    {

        for (int i = 0; i < n; i++)
            tat[i] = proc[i].cpuCycle + wt[i];
    }


    static void avgTime(Process[] proc, int n)
    {
        int[] wt = new int[n], tat = new int[n];
        int  total_wt = 0, total_tat = 0;

        WaitingTime(proc, n, wt);

        TurnAroundTime(proc, n, wt, tat);

        System.out.println("File Name " + " Turn around time");

        for (int i = 0; i < n; i++) {
            total_tat = total_tat + tat[i];
            System.out.println( proc[i].fileName + " " + tat[i]);
        }

        System.out.println("Average turnaround time = " + (float)total_tat / 7);
    }



    public static void main(String[] args) {
        Records[] NewyorkRecords = new Records[]{
                new Records(1, "John Doe", 30, "USA", "New York", "Admitted"),
                new Records(2, "Jane Smith", 25, "USA", "New York", "Outpatient"),
                new Records(3, "Michael Johnson", 40, "USA", "New York", "Dead"),
                new Records(4, "Emily Brown", 35, "USA", "New York", "Admitted"),
                new Records(5, "David Lee", 28, "USA", "New York", "Outpatient"),
                new Records(6, "Sarah Wilson", 45, "USA", "New York", "Admitted"),
                new Records(7, "James Taylor", 32, "USA", "New York", "Outpatient"),
                new Records(8, "Olivia Martinez", 27, "USA", "New York", "Admitted"),
                new Records(9, "William Anderson", 38, "USA", "New York", "Outpatient"),
                new Records(10, "Ava GacpuCycleia", 31, "USA", "New York", "Dead"),
                new Records(11, "Liam Hernandez", 29, "USA", "New York", "Admitted"),
                new Records(12, "Emma Nguyen", 34, "USA", "New York", "Outpatient"),
                new Records(13, "Noah Robinson", 26, "USA", "New York", "Admitted"),
                new Records(14, "Sophia Lewis", 33, "USA", "New York", "Outpatient"),
                new Records(15, "Alexander Hall", 42, "USA", "New York", "Admitted"),
                new Records(16, "Mia Allen", 37, "USA", "New York", "Outpatient"),
                new Records(17, "Ethan Scott", 39, "USA", "New York", "Admitted"),
                new Records(18, "Isabella King", 24, "USA", "New York", "Outpatient"),
                new Records(19, "Aiden Hill", 36, "USA", "New York", "Admitted"),
                new Records(20, "Charlotte Wright", 28, "USA", "New York", "Outpatient"),
                new Records(21, "Harper Green", 41, "USA", "New York", "Admitted"),
                new Records(22, "Mason Adams", 26, "USA", "New York", "Outpatient"),
                new Records(23, "Evelyn Baker", 29, "USA", "New York", "Admitted"),
                new Records(24, "Michaela Rivera", 32, "USA", "New York", "Outpatient"),
                new Records(25, "Lucas Campbell", 35, "USA", "New York", "Admitted"),
                new Records(26, "Madison Ward", 27, "USA", "New York", "Outpatient"),
                new Records(27, "Logan Cox", 30, "USA", "New York", "Admitted"),
                new Records(28, "Chloe Peterson", 38, "USA", "New York", "Outpatient"),
                new Records(29, "Elijah Morris", 33, "USA", "New York", "Admitted"),
                new Records(30, "Grace Hughes", 40, "USA", "New York", "Outpatient"),
                new Records(31, "Emma Long", 31, "USA", "New York", "Admitted"),
                new Records(32, "Alexander Gray", 29, "USA", "New York", "Outpatient"),
                new Records(33, "Isabella Flores", 42, "USA", "New York", "Admitted"),
                new Records(34, "Liam Washington", 37, "USA", "New York", "Outpatient"),
                new Records(35, "Olivia Richardson", 39, "USA", "New York", "Admitted"),
                new Records(36, "Noah Brooks", 24, "USA", "New York", "Outpatient"),
                new Records(37, "Sophia Martin", 36, "USA", "New York", "Admitted"),
                new Records(38, "Ava Hill", 28, "USA", "New York", "Outpatient"),
                new Records(39, "William Reed", 41, "USA", "New York", "Admitted"),
                new Records(40, "Charlotte Ward", 26, "USA", "New York", "Outpatient"),
                new Records(41, "Harper Cox", 29, "USA", "New York", "Admitted"),
                new Records(42, "Mason Kelly", 32, "USA", "New York", "Outpatient"),
                new Records(43, "Evelyn Sanders", 35, "USA", "New York", "Admitted"),
                new Records(44, "Michaela GacpuCycleia", 27, "USA", "New York", "Outpatient"),
                new Records(45, "Lucas Young", 30, "USA", "New York", "Admitted"),
                new Records(46, "Madison Lee", 38, "USA", "New York", "Outpatient"),
                new Records(47, "Logan King", 33, "USA", "New York", "Admitted"),
                new Records(48, "Chloe Nguyen", 42, "USA", "New York", "Outpatient"),
                new Records(49, "Elijah Robinson", 37, "USA", "New York", "Admitted"),
                new Records(50, "Grace Hill", 24, "USA", "New York", "Outpatient"),
                new Records(51, "Emma Brooks", 36, "USA", "New York", "Admitted"),
                new Records(52, "Alexander Sanders", 28, "USA", "New York", "Outpatient"),
                new Records(53, "Isabella Diaz", 41, "USA", "New York", "Admitted"),
                new Records(54, "Liam Martinez", 26, "USA", "New York", "Outpatient"),
                new Records(55, "Olivia Anderson", 29, "USA", "New York", "Admitted"),
                new Records(56, "Noah Wilson", 32, "USA", "New York", "Outpatient"),
                new Records(57, "Sophia Taylor", 35, "USA", "New York", "Admitted"),
                new Records(58, "Ava Smith", 27, "USA", "New York", "Outpatient"),
                new Records(59, "William Johnson", 30, "USA", "New York", "Admitted"),
                new Records(60, "Charlotte Brown", 38, "USA", "New York", "Outpatient"),
                new Records(61, "Harper Lee", 33, "USA", "New York", "Admitted"),
                new Records(62, "Mason Martin", 42, "USA", "New York", "Outpatient"),
                new Records(63, "Evelyn Adams", 37, "USA", "New York", "Admitted"),
                new Records(64, "Michaela Hall", 24, "USA", "New York", "Outpatient"),
                new Records(65, "Lucas Hernandez", 36, "USA", "New York", "Admitted"),
                new Records(66, "Madison Baker", 28, "USA", "New York", "Outpatient"),
                new Records(67, "Logan Scott", 41, "USA", "New York", "Admitted"),
                new Records(68, "Chloe Nguyen", 26, "USA", "New York", "Outpatient"),
                new Records(69, "Elijah Hill", 29, "USA", "New York", "Admitted"),
                new Records(70, "Grace Cox", 32, "USA", "New York", "Outpatient"),
                new Records(71, "Emma Kelly", 35, "USA", "New York", "Admitted"),
                new Records(72, "Alexander Ward", 27, "USA", "New York", "Outpatient"),
                new Records(73, "Isabella Sanders", 30, "USA", "New York", "Admitted"),
                new Records(74, "Liam GacpuCycleia", 38, "USA", "New York", "Outpatient"),
                new Records(75, "Olivia Young", 33, "USA", "New York", "Admitted"),
                new Records(76, "Noah Lee", 24, "USA", "New York", "Outpatient"),
                new Records(77, "Sophia Ward", 36, "USA", "New York", "Admitted"),
                new Records(78, "Ava Baker", 28, "USA", "New York", "Outpatient"),
                new Records(79, "William Rivera", 41, "USA", "New York", "Admitted"),
                new Records(80, "Charlotte Cox", 26, "USA", "New York", "Outpatient"),
                new Records(81, "Harper Nguyen", 29, "USA", "New York", "Admitted"),
                new Records(82, "Mason Hill", 32, "USA", "New York", "Outpatient"),
                new Records(83, "Evelyn Gray", 35, "USA", "New York", "Admitted"),
                new Records(84, "Michaela Flores", 27, "USA", "New York", "Outpatient"),
                new Records(85, "Lucas Washington", 30, "USA", "New York", "Admitted"),
                new Records(86, "Madison Richardson", 38, "USA", "New York", "Outpatient"),
                new Records(87, "Logan Brooks", 33, "USA", "New York", "Admitted"),
                new Records(88, "Chloe Martin", 42, "USA", "New York", "Outpatient"),
                new Records(89, "Elijah Hill", 37, "USA", "New York", "Admitted"),
                new Records(90, "Grace Nguyen", 24, "USA", "New York", "Outpatient"),
                new Records(91, "Emma King", 36, "USA", "New York", "Admitted"),
                new Records(92, "Alexander Cox", 28, "USA", "New York", "Outpatient"),
                new Records(93, "Isabella Lee", 41, "USA", "New York", "Admitted"),
                new Records(94, "Liam Kelly", 26, "USA", "New York", "Outpatient"),
                new Records(95, "Olivia Martin", 29, "USA", "New York", "Admitted"),
                new Records(96, "Noah Hill", 32, "USA", "New York", "Outpatient"),
                new Records(97, "Sophia Sanders", 35, "USA", "New York", "Admitted"),
                new Records(98, "Ava Diaz", 27, "USA", "New York", "Outpatient"),
                new Records(99, "William Martinez", 30, "USA", "New York", "Admitted"),
                new Records(100, "Charlotte Young", 38, "USA", "New York", "Outpatient"),
                new Records(101, "Harper Anderson", 33, "USA", "New York", "Admitted"),
                new Records(102, "Mason Wilson", 42, "USA", "New York", "Outpatient"),
                new Records(103, "Evelyn Taylor", 37, "USA", "New York", "Admitted"),
                new Records(104, "Michaela Hall", 24, "USA", "New York", "Outpatient"),
                new Records(105, "Lucas Johnson", 36, "USA", "New York", "Admitted"),
                new Records(106, "Madison Hernandez", 28, "USA", "New York", "Outpatient"),
                new Records(107, "Logan Baker", 41, "USA", "New York", "Admitted"),
                new Records(108, "Chloe Lee", 26, "USA", "New York", "Outpatient"),
                new Records(109, "Elijah Sanders", 29, "USA", "New York", "Admitted"),
                new Records(110, "Grace GacpuCycleia", 32, "USA", "New York", "Outpatient"),
                new Records(111, "Emma Ward", 35, "USA", "New York", "Admitted"),
                new Records(112, "Alexander Adams", 27, "USA", "New York", "Outpatient"),
                new Records(113, "Isabella Martin", 30, "USA", "New York", "Admitted"),
                new Records(114, "Liam Hill", 38, "USA", "New York", "Outpatient"),
                new Records(115, "Olivia Cox", 33, "USA", "New York", "Admitted"),
                new Records(116, "Noah Nguyen", 24, "USA", "New York", "Outpatient"),
                new Records(117, "Sophia Hernandez", 36, "USA", "New York", "Admitted"),
                new Records(118, "Ava Baker", 28, "USA", "New York", "Outpatient"),
                new Records(119, "William Hill", 41, "USA", "New York", "Admitted"),
                new Records(120, "Charlotte Smith", 26, "USA", "New York", "Outpatient"),
                new Records(121, "Harper Anderson", 29, "USA", "New York", "Admitted"),
                new Records(122, "Mason Johnson", 32, "USA", "New York", "Outpatient"),
                new Records(123, "Evelyn Lee", 35, "USA", "New York", "Admitted"),
                new Records(124, "Michaela Brown", 37, "USA", "New York", "Outpatient"),
                new Records(125, "Lucas Davis", 24, "USA", "New York", "Admitted"),
                new Records(126, "Madison Nguyen", 36, "USA", "New York", "Outpatient"),
                new Records(127, "Logan Harris", 28, "USA", "New York", "Admitted"),
                new Records(128, "Chloe Miller", 41, "USA", "New York", "Outpatient"),
                new Records(129, "Elijah Thompson", 30, "USA", "New York", "Admitted"),
                new Records(130, "Grace Taylor", 33, "USA", "New York", "Outpatient"),
                new Records(131, "Emma Rodriguez", 26, "USA", "New York", "Admitted"),
                new Records(132, "Alexander White", 39, "USA", "New York", "Outpatient"),
                new Records(133, "Isabella Moore", 42, "USA", "New York", "Admitted"),
                new Records(134, "Liam Clark", 27, "USA", "New York", "Outpatient"),
                new Records(135, "Olivia Green", 29, "USA", "New York", "Admitted"),
                new Records(136, "Noah Hall", 32, "USA", "New York", "Outpatient"),
                new Records(137, "Sophia Harris", 35, "USA", "New York", "Admitted"),
                new Records(138, "Ava GacpuCycleia", 38, "USA", "New York", "Outpatient"),
                new Records(139, "William Adams", 24, "USA", "New York", "Admitted"),
                new Records(140, "Charlotte Moore", 36, "USA", "New York", "Outpatient"),
                new Records(141, "Harper Miller", 28, "USA", "New York", "Admitted"),
                new Records(142, "Mason Perez", 31, "USA", "New York", "Outpatient"),
                new Records(143, "Evelyn Cooper", 34, "USA", "New York", "Admitted"),
                new Records(144, "Michaela Taylor", 37, "USA", "New York", "Outpatient"),
                new Records(145, "Lucas Hernandez", 40, "USA", "New York", "Admitted"),
                new Records(146, "Madison Cox", 25, "USA", "New York", "Outpatient"),
                new Records(147, "Logan Hall", 42, "USA", "New York", "Admitted"),
                new Records(148, "Chloe Williams", 29, "USA", "New York", "Outpatient"),
                new Records(149, "Elijah Hill", 32, "USA", "New York", "Admitted"),
                new Records(150, "Grace Perez", 39, "USA", "New York", "Outpatient")
        };

        Records[] londonRecords = {
                new Records(1, "James Smith", 30, "UK", "London", "Admitted"),
                new Records(2, "Emma Johnson", 25, "UK", "London", "Outpatient"),
                new Records(3, "William Brown", 40, "UK", "London", "Dead"),
                new Records(4, "Olivia Wilson", 35, "UK", "London", "Admitted"),
                new Records(5, "Alexander Taylor", 28, "UK", "London", "Outpatient"),
                new Records(6, "Sophia Martinez", 45, "UK", "London", "Admitted"),
                new Records(7, "Liam Anderson", 32, "UK", "London", "Outpatient"),
                new Records(8, "Isabella Thomas", 27, "UK", "London", "Admitted"),
                new Records(9, "Noah Clark", 38, "UK", "London", "Outpatient"),
                new Records(10, "Charlotte Harris", 31, "UK", "London", "Dead"),
                new Records(11, "Mia Davies", 29, "UK", "London", "Admitted"),
                new Records(12, "George Walker", 34, "UK", "London", "Outpatient"),
                new Records(13, "Amelia Evans", 26, "UK", "London", "Admitted"),
                new Records(14, "Mason Roberts", 33, "UK", "London", "Outpatient"),
                new Records(15, "Emily Wright", 42, "UK", "London", "Admitted"),
                new Records(16, "Ethan Jackson", 37, "UK", "London", "Outpatient"),
                new Records(17, "Isabella Adams", 39, "UK", "London", "Admitted"),
                new Records(18, "Ava White", 24, "UK", "London", "Outpatient"),
                new Records(19, "Aiden Green", 36, "UK", "London", "Admitted"),
                new Records(20, "Sophia Harris", 28, "UK", "London", "Outpatient"),
                new Records(21, "Harry Hall", 41, "UK", "London", "Admitted"),
                new Records(22, "Olivia Parker", 26, "UK", "London", "Outpatient"),
                new Records(23, "Charlie Phillips", 29, "UK", "London", "Admitted"),
                new Records(24, "Jessica Scott", 32, "UK", "London", "Outpatient"),
                new Records(25, "Jack Bennett", 35, "UK", "London", "Admitted"),
                new Records(26, "Poppy Watson", 27, "UK", "London", "Outpatient"),
                new Records(27, "Leo Morris", 30, "UK", "London", "Admitted"),
                new Records(28, "Isla Wood", 38, "UK", "London", "Outpatient"),
                new Records(29, "Thomas Price", 33, "UK", "London", "Admitted"),
                new Records(30, "Grace Baker", 24, "UK", "London", "Outpatient"),
                new Records(31, "Alfie Brooks", 36, "UK", "London", "Admitted"),
                new Records(32, "Ella Bell", 28, "UK", "London", "Outpatient"),
                new Records(33, "Reuben Cox", 41, "UK", "London", "Admitted"),
                new Records(34, "Daisy Hill", 26, "UK", "London", "Outpatient"),
                new Records(35, "Arthur Richardson", 39, "UK", "London", "Admitted"),
                new Records(36, "Lilly Moore", 32, "UK", "London", "Outpatient"),
                new Records(37, "Lucas Walker", 24, "UK", "London", "Admitted"),
                new Records(38, "Aria Evans", 36, "UK", "London", "Outpatient"),
                new Records(39, "Edward Adams", 29, "UK", "London", "Admitted"),
                new Records(40, "Florence Gray", 42, "UK", "London", "Outpatient"),
                new Records(41, "Theo Green", 27, "UK", "London", "Admitted"),
                new Records(42, "Evie Rogers", 30, "UK", "London", "Outpatient"),
                new Records(43, "Harrison Morris", 35, "UK", "London", "Admitted"),
                new Records(44, "Isabella Cox", 28, "UK", "London", "Outpatient"),
                new Records(45, "Matilda Reed", 41, "UK", "London", "Admitted"),
                new Records(46, "Oscar Ward", 26, "UK", "London", "Outpatient"),
                new Records(47, "Elsie Murray", 32, "UK", "London", "Admitted"),
                new Records(48, "Logan Simpson", 37, "UK", "London", "Outpatient"),
                new Records(49, "Millie Fuller", 24, "UK", "London", "Admitted"),
                new Records(50, "Dylan Patel", 36, "UK", "London", "Outpatient"),
                new Records(51, "Amber Bryant", 29, "UK", "London", "Admitted"),
                new Records(52, "Max Turner", 38, "UK", "London", "Outpatient"),
                new Records(53, "Harper West", 31, "UK", "London", "Admitted"),
                new Records(54, "Ellie Powell", 25, "UK", "London", "Outpatient"),
                new Records(55, "Joseph Watson", 42, "UK", "London", "Admitted"),
                new Records(56, "Ava Russell", 27, "UK", "London", "Outpatient"),
                new Records(57, "Harry Murray", 30, "UK", "London", "Admitted"),
                new Records(58, "Willow Cook", 35, "UK", "London", "Outpatient"),
                new Records(59, "Charlie Ward", 28, "UK", "London", "Admitted"),
                new Records(60, "Sienna Patel", 41, "UK", "London", "Outpatient"),
                new Records(61, "Elliot Hopkins", 26, "UK", "London", "Admitted"),
                new Records(62, "Sofia Price", 33, "UK", "London", "Outpatient"),
                new Records(63, "Holly Butler", 36, "UK", "London", "Admitted"),
                new Records(64, "Aaron Clark", 24, "UK", "London", "Outpatient"),
                new Records(65, "DacpuCycleie Palmer", 39, "UK", "London", "Admitted"),
                new Records(66, "Freddie James", 32, "UK", "London", "Outpatient"),
                new Records(67, "Georgia Wood", 25, "UK", "London", "Admitted"),
                new Records(68, "Alfie Turner", 40, "UK", "London", "Outpatient"),
                new Records(69, "Eva Simpson", 27, "UK", "London", "Admitted"),
                new Records(70, "Ollie Stewart", 34, "UK", "London", "Outpatient"),
                new Records(71, "Florence White", 38, "UK", "London", "Admitted"),
                new Records(72, "Jake Hunt", 29, "UK", "London", "Outpatient"),
                new Records(73, "Emilia Bennett", 31, "UK", "London", "Admitted"),
                new Records(74, "AcpuCyclehie Rogers", 42, "UK", "London", "Outpatient"),
                new Records(75, "Imogen Fisher", 26, "UK", "London", "Admitted"),
                new Records(76, "Hugo Bell", 37, "UK", "London", "Outpatient"),
                new Records(77, "Lottie Ward", 24, "UK", "London", "Admitted"),
                new Records(78, "George Scott", 36, "UK", "London", "Outpatient"),
                new Records(79, "Evie Fisher", 28, "UK", "London", "Admitted"),
                new Records(80, "Arthur Stewart", 41, "UK", "London", "Outpatient"),
                new Records(81, "Ivy Wood", 30, "UK", "London", "Admitted"),
                new Records(82, "Riley Martin", 35, "UK", "London", "Outpatient"),
                new Records(83, "Layla Cox", 27, "UK", "London", "Admitted"),
                new Records(84, "Jasper Hill", 39, "UK", "London", "Outpatient"),
                new Records(85, "Freya Russell", 32, "UK", "London", "Admitted"),
                new Records(86, "Finley Wright", 25, "UK", "London", "Outpatient"),
                new Records(87, "Amelia Campbell", 40, "UK", "London", "Admitted"),
                new Records(88, "Oscar Turner", 33, "UK", "London", "Outpatient"),
                new Records(89, "Isabella Thomas", 28, "UK", "London", "Admitted"),
                new Records(90, "Jacob Martin", 31, "UK", "London", "Outpatient"),
                new Records(91, "Elsie Ward", 34, "UK", "London", "Admitted"),
                new Records(92, "Molly Rogers", 24, "UK", "London", "Outpatient"),
                new Records(93, "Toby Powell", 36, "UK", "London", "Admitted"),
                new Records(94, "Summer Hall", 27, "UK", "London", "Outpatient"),
                new Records(95, "Felix Wood", 42, "UK", "London", "Admitted"),
                new Records(96, "Lola Cox", 29, "UK", "London", "Outpatient"),
                new Records(97, "Joshua Simpson", 38, "UK", "London", "Admitted"),
                new Records(98, "Phoebe Fisher", 26, "UK", "London", "Outpatient"),
                new Records(99, "Harrison Reed", 39, "UK", "London", "Admitted"),
                new Records(100, "Ella Carter", 30, "UK", "London", "Outpatient")
        };
        Records[] LagosRecords = {
                new Records(1, "Ahmed Mohammed", 30, "Nigeria", "Lagos", "Admitted"),
                new Records(2, "Fatima Ibrahim", 25, "Nigeria", "Lagos", "Outpatient"),
                new Records(3, "Yusuf Abubakar", 40, "Nigeria", "Lagos", "Dead"),
                new Records(4, "Aisha Musa", 35, "Nigeria", "Lagos", "Admitted"),
                new Records(5, "Abdullahi Aliyu", 28, "Nigeria", "Lagos", "Outpatient"),
                new Records(6, "Zainab Suleiman", 45, "Nigeria", "Lagos", "Admitted"),
                new Records(7, "Musa Bello", 32, "Nigeria", "Lagos", "Outpatient"),
                new Records(8, "Mariam Lawal", 27, "Nigeria", "Lagos", "Admitted"),
                new Records(9, "Abubakar Hassan", 38, "Nigeria", "Lagos", "Outpatient"),
                new Records(10, "Amina Abdullahi", 31, "Nigeria", "Lagos", "Dead"),
                new Records(11, "Ibrahim Sani", 29, "Nigeria", "Lagos", "Admitted"),
                new Records(12, "Halima Adamu", 34, "Nigeria", "Lagos", "Outpatient"),
                new Records(13, "Aliyu Dauda", 26, "Nigeria", "Lagos", "Admitted"),
                new Records(14, "Hauwa Garba", 33, "Nigeria", "Lagos", "Outpatient"),
                new Records(15, "Sadiq Abdullahi", 42, "Nigeria", "Lagos", "Admitted"),
                new Records(16, "Fatimah Usman", 37, "Nigeria", "Lagos", "Outpatient"),
                new Records(17, "Abubakar Lawal", 39, "Nigeria", "Lagos", "Admitted"),
                new Records(18, "Hassan Muhammad", 24, "Nigeria", "Lagos", "Outpatient"),
                new Records(19, "Abdulrahman Bala", 36, "Nigeria", "Lagos", "Admitted"),
                new Records(20, "Rukayya Mohammed", 28, "Nigeria", "Lagos", "Outpatient"),
                new Records(21, "Fatima Ibrahim", 41, "Nigeria", "Lagos", "Admitted"),
                new Records(22, "Usman Musa", 26, "Nigeria", "Lagos", "Outpatient"),
                new Records(23, "Hadiza Aliyu", 29, "Nigeria", "Lagos", "Admitted"),
                new Records(24, "Ahmed Abdullahi", 32, "Nigeria", "Lagos", "Outpatient"),
                new Records(25, "Maryam Abubakar", 35, "Nigeria", "Lagos", "Admitted"),
                new Records(26, "Aliyu Garba", 27, "Nigeria", "Lagos", "Outpatient"),
                new Records(27, "Rabi Suleiman", 30, "Nigeria", "Lagos", "Admitted"),
                new Records(28, "Abdulazeez Bello", 38, "Nigeria", "Lagos", "Outpatient"),
                new Records(29, "Khadija Lawal", 33, "Nigeria", "Lagos", "Admitted"),
                new Records(30, "Habibu Ibrahim", 24, "Nigeria", "Lagos", "Outpatient"),
                new Records(31, "Hauwa Sani", 36, "Nigeria", "Lagos", "Admitted"),
                new Records(32, "Musa Bala", 28, "Nigeria", "Lagos", "Outpatient"),
                new Records(33, "Halima Yusuf", 41, "Nigeria", "Lagos", "Admitted"),
                new Records(34, "Isa Adamu", 26, "Nigeria", "Lagos", "Outpatient"),
                new Records(35, "Fatima Umar", 39, "Nigeria", "Lagos", "Admitted"),
                new Records(36, "Abubakar Ahmed", 32, "Nigeria", "Lagos", "Outpatient"),
                new Records(37, "Hafsat Ibrahim", 24, "Nigeria", "Lagos", "Admitted"),
                new Records(38, "Yusuf Mohammed", 36, "Nigeria", "Lagos", "Outpatient"),
                new Records(39, "Mariam Abubakar", 29, "Nigeria", "Lagos", "Admitted"),
                new Records(40, "Ahmed Suleiman", 42, "Nigeria", "Lagos", "Outpatient"),
                new Records(41, "Fatima Bello", 27, "Nigeria", "Lagos", "Admitted"),
                new Records(42, "Usman Garba", 30, "Nigeria", "Lagos", "Outpatient"),
                new Records(43, "Rukayya Abdullahi", 35, "Nigeria", "Lagos", "Admitted"),
                new Records(44, "Abdullahi Lawal", 28, "Nigeria", "Lagos", "Outpatient"),
                new Records(45, "Halima Yusuf", 41, "Nigeria", "Lagos", "Admitted"),
                new Records(46, "Ibrahim Adamu", 26, "Nigeria", "Lagos", "Outpatient"),
                new Records(47, "Hassana Abubakar", 39, "Nigeria", "Lagos", "Admitted"),
                new Records(48, "Abubakar Sani", 32, "Nigeria", "Lagos", "Outpatient"),
                new Records(49, "Amina Ibrahim", 37, "Nigeria", "Lagos", "Admitted"),
                new Records(50, "Halima Musa", 24, "Nigeria", "Lagos", "Outpatient"),
                new Records(51, "Isa Abubakar", 36, "Nigeria", "Lagos", "Admitted"),
                new Records(52, "Habiba Aliyu", 28, "Nigeria", "Lagos", "Outpatient"),
                new Records(53, "Aliyu Abdullahi", 41, "Nigeria", "Lagos", "Admitted"),
                new Records(54, "Fatima Bala", 25, "Nigeria", "Lagos", "Outpatient"),
                new Records(55, "Abdulmumin Ibrahim", 30, "Nigeria", "Lagos", "Admitted"),
                new Records(56, "Zainab Mohammed", 35, "Nigeria", "Lagos", "Outpatient"),
                new Records(57, "Abubakar Ahmed", 27, "Nigeria", "Lagos", "Admitted"),
                new Records(58, "Hadiza Suleiman", 42, "Nigeria", "Lagos", "Outpatient"),
                new Records(59, "Yusuf Ibrahim", 29, "Nigeria", "Lagos", "Admitted"),
                new Records(60, "Mariam Hassan", 34, "Nigeria", "Lagos", "Outpatient"),
                new Records(61, "Ahmed Adamu", 26, "Nigeria", "Lagos", "Admitted"),
                new Records(62, "Fatima Musa", 31, "Nigeria", "Lagos", "Outpatient"),
                new Records(63, "Abdulazeez Bello", 36, "Nigeria", "Lagos", "Admitted"),
                new Records(64, "Rukayya Usman", 24, "Nigeria", "Lagos", "Outpatient"),
                new Records(65, "Usman Bala", 39, "Nigeria", "Lagos", "Admitted"),
                new Records(66, "Halima Abdullahi", 32, "Nigeria", "Lagos", "Outpatient"),
                new Records(67, "Aisha Lawal", 37, "Nigeria", "Lagos", "Admitted"),
                new Records(68, "Ibrahim Muhammad", 28, "Nigeria", "Lagos", "Outpatient"),
                new Records(69, "Mariam Musa", 41, "Nigeria", "Lagos", "Admitted"),
                new Records(70, "Abubakar Lawal", 25, "Nigeria", "Lagos", "Outpatient"),
                new Records(71, "Hadiza Abdullahi", 30, "Nigeria", "Lagos", "Admitted"),
                new Records(72, "Yusuf Ibrahim", 35, "Nigeria", "Lagos", "Outpatient"),
                new Records(73, "Fatima Abubakar", 38, "Nigeria", "Lagos", "Admitted"),
                new Records(74, "Ahmed Sani", 29, "Nigeria", "Lagos", "Outpatient"),
                new Records(75, "Hauwa Ibrahim", 40, "Nigeria", "Lagos", "Admitted"),
                new Records(76, "Abdullahi Adamu", 27, "Nigeria", "Lagos", "Outpatient"),
                new Records(77, "Maryam Hassan", 32, "Nigeria", "Lagos", "Admitted"),
                new Records(78, "Abubakar Musa", 34, "Nigeria", "Lagos", "Outpatient"),
                new Records(79, "Halima Ibrahim", 24, "Nigeria", "Lagos", "Admitted"),
                new Records(80, "Ibrahim Abdullahi", 36, "Nigeria", "Lagos", "Outpatient"),
                new Records(81, "Fatima Mohammed", 28, "Nigeria", "Lagos", "Admitted"),
                new Records(82, "Usman Ahmed", 33, "Nigeria", "Lagos", "Outpatient"),
                new Records(83, "Rukayya Bello", 39, "Nigeria", "Lagos", "Admitted"),
                new Records(84, "Abdulmumin Suleiman", 26, "Nigeria", "Lagos", "Outpatient"),
                new Records(85, "Zainab Lawal", 41, "Nigeria", "Lagos", "Admitted"),
                new Records(86, "Abubakar Yusuf", 25, "Nigeria", "Lagos", "Outpatient"),
                new Records(87, "Hadiza Abubakar", 30, "Nigeria", "Lagos", "Admitted"),
                new Records(88, "Yusuf Suleiman", 37, "Nigeria", "Lagos", "Outpatient"),
                new Records(89, "Mariam Ibrahim", 42, "Nigeria", "Lagos", "Admitted"),
                new Records(90, "Ahmed Bello", 29, "Nigeria", "Lagos", "Outpatient"),
                new Records(91, "Fatima Mohammed", 36, "Nigeria", "Lagos", "Admitted"),
                new Records(92, "Usman Abdullahi", 24, "Nigeria", "Lagos", "Outpatient"),
                new Records(93, "Rukayya Adamu", 38, "Nigeria", "Lagos", "Admitted"),
                new Records(94, "Abdullahi Hassan", 27, "Nigeria", "Lagos", "Outpatient"),
                new Records(95, "Halima Musa", 35, "Nigeria", "Lagos", "Admitted"),
                new Records(96, "Ibrahim Mohammed", 30, "Nigeria", "Lagos", "Outpatient"),
                new Records(97, "Mariam Ibrahim", 41, "Nigeria", "Lagos", "Admitted"),
                new Records(98, "Abubakar Yusuf", 28, "Nigeria", "Lagos", "Outpatient"),
                new Records(99, "Fatima Suleiman", 39, "Nigeria", "Lagos", "Admitted"),
                new Records(100, "Usman Adamu", 26, "Nigeria", "Lagos", "Outpatient"),
                new Records(101, "Rukayya Abubakar", 34, "Nigeria", "Lagos", "Admitted"),
                new Records(102, "Abdullahi Ibrahim", 37, "Nigeria", "Lagos", "Outpatient"),
                new Records(103, "Hadiza Bello", 25, "Nigeria", "Lagos", "Admitted"),
                new Records(104, "Yusuf Abubakar", 32, "Nigeria", "Lagos", "Outpatient"),
                new Records(105, "Mariam Lawal", 36, "Nigeria", "Lagos", "Admitted"),
                new Records(106, "Ahmed Hassan", 28, "Nigeria", "Lagos", "Outpatient"),
                new Records(107, "Fatima Abdullahi", 41, "Nigeria", "Lagos", "Admitted"),
                new Records(108, "Usman Mohammed", 24, "Nigeria", "Lagos", "Outpatient"),
                new Records(109, "Rukayya Ibrahim", 39, "Nigeria", "Lagos", "Admitted"),
                new Records(110, "Abdullahi Suleiman", 27, "Nigeria", "Lagos", "Outpatient"),
                new Records(111, "Halima Abdullahi", 35, "Nigeria", "Lagos", "Admitted"),
                new Records(112, "Ibrahim Musa", 30, "Nigeria", "Lagos", "Outpatient"),
                new Records(113, "Mariam Bala", 42, "Nigeria", "Lagos", "Admitted"),
                new Records(114, "Abubakar Ahmed", 29, "Nigeria", "Lagos", "Outpatient"),
                new Records(115, "Fatima Musa", 36, "Nigeria", "Lagos", "Admitted"),
                new Records(116, "Usman Ibrahim", 26, "Nigeria", "Lagos", "Outpatient"),
                new Records(117, "Rukayya Lawal", 38, "Nigeria", "Lagos", "Admitted"),
                new Records(118, "Abdulmumin Mohammed", 27, "Nigeria", "Lagos", "Outpatient"),
                new Records(119, "Zainab Ibrahim", 40, "Nigeria", "Lagos", "Admitted"),
                new Records(120, "Abubakar Abdullahi", 31, "Nigeria", "Lagos", "Outpatient")

        };
        Records[] JohannesburgRecords = {
                new Records(1, "Lerato Mabuza", 30, "South Africa", "Johannesburg", "Admitted"),
                new Records(2, "Thabo Kgomo", 25, "South Africa", "Johannesburg", "Outpatient"),
                new Records(3, "Nomfundo Ndlovu", 40, "South Africa", "Johannesburg", "Dead"),
                new Records(4, "Khanyisile Sithole", 35, "South Africa", "Johannesburg", "Admitted"),
                new Records(5, "Andile Nkosi", 28, "South Africa", "Johannesburg", "Outpatient"),
                new Records(6, "Refiloe Motsepe", 45, "South Africa", "Johannesburg", "Admitted"),
                new Records(7, "Sipho Khumalo", 32, "South Africa", "Johannesburg", "Outpatient"),
                new Records(8, "Nomzamo Ngubane", 27, "South Africa", "Johannesburg", "Admitted"),
                new Records(9, "Lwandile Dlamini", 38, "South Africa", "Johannesburg", "Outpatient"),
                new Records(10, "Nomthandazo Mkhize", 31, "South Africa", "Johannesburg", "Dead"),
                new Records(11, "Bongani Moyo", 29, "South Africa", "Johannesburg", "Admitted"),
                new Records(12, "Zanele Khumalo", 34, "South Africa", "Johannesburg", "Outpatient"),
                new Records(13, "Phumlani Zulu", 26, "South Africa", "Johannesburg", "Admitted"),
                new Records(14, "Siyabonga Mbatha", 33, "South Africa", "Johannesburg", "Outpatient"),
                new Records(15, "Nompumelelo Buthelezi", 42, "South Africa", "Johannesburg", "Admitted"),
                new Records(16, "Lungelo Mkhwanazi", 37, "South Africa", "Johannesburg", "Outpatient"),
                new Records(17, "Nokuthula Khumalo", 39, "South Africa", "Johannesburg", "Admitted"),
                new Records(18, "Simphiwe Dube", 24, "South Africa", "Johannesburg", "Outpatient"),
                new Records(19, "Mthokozisi Mthembu", 36, "South Africa", "Johannesburg", "Admitted"),
                new Records(20, "Nonhlanhla Nkosi", 28, "South Africa", "Johannesburg", "Outpatient"),
                new Records(21, "Njabulo Ntuli", 41, "South Africa", "Johannesburg", "Admitted"),
                new Records(22, "Khethiwe Zulu", 26, "South Africa", "Johannesburg", "Outpatient"),
                new Records(23, "Nokwazi Ngcobo", 29, "South Africa", "Johannesburg", "Admitted"),
                new Records(24, "Senzo Sithole", 32, "South Africa", "Johannesburg", "Outpatient"),
                new Records(25, "Nompilo Khumalo", 35, "South Africa", "Johannesburg", "Admitted"),
                new Records(26, "Luthando Mthethwa", 27, "South Africa", "Johannesburg", "Outpatient"),
                new Records(27, "Thandeka Ncube", 30, "South Africa", "Johannesburg", "Admitted"),
                new Records(28, "Sizwe Ngwenya", 38, "South Africa", "Johannesburg", "Outpatient"),
                new Records(29, "Ayanda Mokoena", 33, "South Africa", "Johannesburg", "Admitted"),
                new Records(30, "Nompumelelo Khumalo", 40, "South Africa", "Johannesburg", "Outpatient"),
                new Records(31, "Bhekani Ndlovu", 31, "South Africa", "Johannesburg", "Admitted"),
                new Records(32, "Siphiwe Nxumalo", 29, "South Africa", "Johannesburg", "Outpatient"),
                new Records(33, "Sibusiso Mhlongo", 42, "South Africa", "Johannesburg", "Admitted"),
                new Records(34, "Zinhle Dlamini", 37, "South Africa", "Johannesburg", "Outpatient"),
                new Records(35, "Nomvula Khumalo", 39, "South Africa", "Johannesburg", "Admitted"),
                new Records(36, "Thabang Ndlovu", 24, "South Africa", "Johannesburg", "Outpatient"),
                new Records(37, "Mandla Sithole", 36, "South Africa", "Johannesburg", "Admitted"),
                new Records(38, "Nthabiseng Khumalo", 28, "South Africa", "Johannesburg", "Outpatient"),
                new Records(39, "Lerato Nkosi", 41, "South Africa", "Johannesburg", "Admitted"),
                new Records(40, "Mpho Mhlanga", 26, "South Africa", "Johannesburg", "Outpatient"),
                new Records(41, "Lebohang Mabena", 36, "South Africa", "Johannesburg", "Admitted"),
                new Records(42, "Buhle Zulu", 29, "South Africa", "Johannesburg", "Outpatient"),
                new Records(43, "Noluthando Nkosi", 35, "South Africa", "Johannesburg", "Admitted"),
                new Records(44, "Lungile Mkhize", 24, "South Africa", "Johannesburg", "Outpatient"),
                new Records(45, "Mlungisi Mbatha", 36, "South Africa", "Johannesburg", "Admitted"),
                new Records(46, "Lindiwe Khumalo", 28, "South Africa", "Johannesburg", "Outpatient"),
                new Records(47, "Sanele Zondo", 33, "South Africa", "Johannesburg", "Admitted"),
                new Records(48, "Sibongile Moyo", 42, "South Africa", "Johannesburg", "Outpatient"),
                new Records(49, "Nkosinathi Dube", 29, "South Africa", "Johannesburg", "Admitted"),
                new Records(50, "Thandiwe Buthelezi", 38, "South Africa", "Johannesburg", "Outpatient"),
                new Records(51, "Bhekizizwe Zuma", 31, "South Africa", "Johannesburg", "Admitted"),
                new Records(52, "Ayanda Mthembu", 26, "South Africa", "Johannesburg", "Outpatient"),
                new Records(53, "Nomsa Mkhize", 41, "South Africa", "Johannesburg", "Admitted"),
                new Records(54, "Luthando Ngcobo", 25, "South Africa", "Johannesburg", "Outpatient"),
                new Records(55, "Londiwe Zungu", 30, "South Africa", "Johannesburg", "Admitted"),
                new Records(56, "Mlungisi Nxumalo", 35, "South Africa", "Johannesburg", "Outpatient"),
                new Records(57, "Sipho Dlamini", 27, "South Africa", "Johannesburg", "Admitted"),
                new Records(58, "Bonginkosi Khumalo", 42, "South Africa", "Johannesburg", "Outpatient"),
                new Records(59, "Nompumelelo Ndlovu", 29, "South Africa", "Johannesburg", "Admitted"),
                new Records(60, "Thando Nkosi", 34, "South Africa", "Johannesburg", "Outpatient"),
                new Records(61, "Zanele Sithole", 36, "South Africa", "Johannesburg", "Admitted"),
                new Records(62, "Mandla Mokoena", 24, "South Africa", "Johannesburg", "Outpatient"),
                new Records(63, "Sibongile Ncube", 39, "South Africa", "Johannesburg", "Admitted"),
                new Records(64, "Nkosinathi Ngwenya", 27, "South Africa", "Johannesburg", "Outpatient"),
                new Records(65, "Thabiso Mabuza", 35, "South Africa", "Johannesburg", "Admitted"),
                new Records(66, "Lindiwe Moyo", 28, "South Africa", "Johannesburg", "Outpatient"),
                new Records(67, "Sanele Khumalo", 40, "South Africa", "Johannesburg", "Admitted"),
                new Records(68, "Mthokozisi Mabaso", 33, "South Africa", "Johannesburg", "Outpatient"),
                new Records(69, "Nompumelelo Ngubane", 39, "South Africa", "Johannesburg", "Admitted"),
                new Records(70, "Simphiwe Ndlovu", 25, "South Africa", "Johannesburg", "Outpatient"),
                new Records(71, "Nomcebo Dube", 30, "South Africa", "Johannesburg", "Admitted"),
                new Records(72, "Phumlani Mthethwa", 37, "South Africa", "Johannesburg", "Outpatient"),
                new Records(73, "Thembeka Zulu", 42, "South Africa", "Johannesburg", "Admitted"),
                new Records(74, "Andiswa Buthelezi", 29, "South Africa", "Johannesburg", "Outpatient"),
                new Records(75, "Zandile Dlamini", 36, "South Africa", "Johannesburg", "Admitted"),
                new Records(76, "Bhekisisa Mhlongo", 24, "South Africa", "Johannesburg", "Outpatient"),
                new Records(77, "Nokuthula Mkhize", 38, "South Africa", "Johannesburg", "Admitted"),
                new Records(78, "Thulani Zondo", 27, "South Africa", "Johannesburg", "Outpatient"),
                new Records(79, "Lerato Moyo", 40, "South Africa", "Johannesburg", "Admitted"),
                new Records(80, "Lungile Khumalo", 31, "South Africa", "Johannesburg", "Outpatient"),
                new Records(81, "Nomfundo Nkosi", 26, "South Africa", "Johannesburg", "Admitted"),
                new Records(82, "Siphiwe Ndaba", 33, "South Africa", "Johannesburg", "Outpatient"),
                new Records(83, "Noluthando Mabuza", 39, "South Africa", "Johannesburg", "Admitted"),
                new Records(84, "Mandla Mhlanga", 28, "South Africa", "Johannesburg", "Outpatient"),
                new Records(85, "Buhle Khumalo", 41, "South Africa", "Johannesburg", "Admitted"),
                new Records(86, "Nkosinathi Mkhwanazi", 25, "South Africa", "Johannesburg", "Outpatient"),
                new Records(87, "Nonhlanhla Ngwenya", 30, "South Africa", "Johannesburg", "Admitted"),
                new Records(88, "Mpho Nkosi", 37, "South Africa", "Johannesburg", "Outpatient")
        };
        Records[] WindhoekRecords = {
                new Records(1, "Johanna van Wyk", 30, "Namibia", "Windhoek", "Admitted"),
                new Records(2, "Jacobus Swart", 25, "Namibia", "Windhoek", "Outpatient"),
                new Records(3, "Maria Amadhila", 40, "Namibia", "Windhoek", "Dead"),
                new Records(4, "Simon Nakale", 35, "Namibia", "Windhoek", "Admitted"),
                new Records(5, "Anna Shikongo", 28, "Namibia", "Windhoek", "Outpatient"),
                new Records(6, "David Nghipandulwa", 45, "Namibia", "Windhoek", "Admitted"),
                new Records(7, "Lydia Kamanya", 32, "Namibia", "Windhoek", "Outpatient"),
                new Records(8, "Paulus Kandjou", 27, "Namibia", "Windhoek", "Admitted"),
                new Records(9, "Helena Shilongo", 38, "Namibia", "Windhoek", "Outpatient"),
                new Records(10, "Andreas Uupindi", 31, "Namibia", "Windhoek", "Dead"),
                new Records(11, "Namutenya Haindongo", 29, "Namibia", "Windhoek", "Admitted"),
                new Records(12, "Festus Amunyela", 34, "Namibia", "Windhoek", "Outpatient"),
                new Records(13, "Eva Shikwambi", 26, "Namibia", "Windhoek", "Admitted"),
                new Records(14, "Thomas Shipena", 33, "Namibia", "Windhoek", "Outpatient"),
                new Records(15, "Elina Uusiku", 42, "Namibia", "Windhoek", "Admitted")
        };
        Records[] ShanghaiRecords = {
                new Records(1, "Zhang Wei", 30, "China", "Shanghai", "Admitted"),
                new Records(2, "Wang Hong", 25, "China", "Shanghai", "Outpatient"),
                new Records(3, "Li Ming", 40, "China", "Shanghai", "Dead"),
                new Records(4, "Liu Yan", 35, "China", "Shanghai", "Admitted"),
                new Records(5, "Chen Xiaojun", 28, "China", "Shanghai", "Outpatient"),
                new Records(6, "Yang Lei", 45, "China", "Shanghai", "Admitted"),
                new Records(7, "Zhao Xin", 32, "China", "Shanghai", "Outpatient"),
                new Records(8, "Huang Lin", 27, "China", "Shanghai", "Admitted"),
                new Records(9, "Wu Qiang", 38, "China", "Shanghai", "Outpatient"),
                new Records(10, "Zhou Jing", 31, "China", "Shanghai", "Dead"),
                new Records(11, "Xu Fang", 29, "China", "Shanghai", "Admitted"),
                new Records(12, "Sun Jing", 34, "China", "Shanghai", "Outpatient"),
                new Records(13, "He Ying", 26, "China", "Shanghai", "Admitted"),
                new Records(14, "Gao Peng", 33, "China", "Shanghai", "Outpatient"),
                new Records(15, "Zhu Wei", 42, "China", "Shanghai", "Admitted"),
                new Records(16, "Li Na", 37, "China", "Shanghai", "Outpatient"),
                new Records(17, "Xie Jun", 39, "China", "Shanghai", "Admitted"),
                new Records(18, "Tang Xiao", 24, "China", "Shanghai", "Outpatient"),
                new Records(19, "Cheng Fang", 36, "China", "Shanghai", "Admitted"),
                new Records(20, "Yu Xin", 28, "China", "Shanghai", "Outpatient"),
                new Records(21, "Wang Jun", 41, "China", "Shanghai", "Admitted"),
                new Records(22, "Chen Wei", 26, "China", "Shanghai", "Outpatient"),
                new Records(23, "Zhang Xiao", 29, "China", "Shanghai", "Admitted"),
                new Records(24, "Liu Fang", 32, "China", "Shanghai", "Outpatient"),
                new Records(25, "Hu Lei", 35, "China", "Shanghai", "Admitted"),
                new Records(26, "Xu Xiao", 27, "China", "Shanghai", "Outpatient"),
                new Records(27, "Wu Jing", 30, "China", "Shanghai", "Admitted"),
                new Records(28, "Zheng Wei", 38, "China", "Shanghai", "Outpatient"),
                new Records(29, "Wang Jing", 33, "China", "Shanghai", "Admitted"),
                new Records(30, "Li Hong", 24, "China", "Shanghai", "Outpatient"),
                new Records(31, "Chen Lei", 36, "China", "Shanghai", "Admitted"),
                new Records(32, "Yang Xiao", 28, "China", "Shanghai", "Outpatient"),
                new Records(33, "Zhu Jun", 41, "China", "Shanghai", "Admitted"),
                new Records(34, "Liu Jing", 26, "China", "Shanghai", "Outpatient"),
                new Records(35, "Sun Wei", 39, "China", "Shanghai", "Admitted"),
                new Records(36, "Gao Fang", 32, "China", "Shanghai", "Outpatient"),
                new Records(37, "Zhao Xiaojie", 30, "China", "Shanghai", "Admitted"),
                new Records(38, "Wu Fang", 28, "China", "Shanghai", "Outpatient"),
                new Records(39, "Zhou Lei", 41, "China", "Shanghai", "Admitted"),
                new Records(40, "Xu Min", 26, "China", "Shanghai", "Outpatient"),
                new Records(41, "Huang Fang", 36, "China", "Shanghai", "Admitted"),
                new Records(42, "Yu Jing", 29, "China", "Shanghai", "Outpatient"),
                new Records(43, "Wang Lei", 39, "China", "Shanghai", "Admitted"),
                new Records(44, "Li Xia", 25, "China", "Shanghai", "Outpatient"),
                new Records(45, "Zhang Hong", 36, "China", "Shanghai", "Admitted"),
                new Records(46, "Liu Xin", 28, "China", "Shanghai", "Outpatient"),
                new Records(47, "Chen Wei", 33, "China", "Shanghai", "Admitted"),
                new Records(48, "Xie Ling", 42, "China", "Shanghai", "Outpatient"),
                new Records(49, "Tang Wei", 29, "China", "Shanghai", "Admitted"),
                new Records(50, "Yu Min", 34, "China", "Shanghai", "Outpatient"),
                new Records(51, "Wang Fang", 31, "China", "Shanghai", "Admitted"),
                new Records(52, "Cheng Xiao", 26, "China", "Shanghai", "Outpatient"),
                new Records(53, "Zhu Fang", 39, "China", "Shanghai", "Admitted"),
                new Records(54, "Sun Min", 25, "China", "Shanghai", "Outpatient"),
                new Records(55, "Hu Jing", 30, "China", "Shanghai", "Admitted"),
                new Records(56, "Xu Wei", 37, "China", "Shanghai", "Outpatient"),
                new Records(57, "Wu Lei", 41, "China", "Shanghai", "Admitted"),
                new Records(58, "Zheng Hong", 27, "China", "Shanghai", "Outpatient"),
                new Records(59, "Wang Xiao", 36, "China", "Shanghai", "Admitted"),
                new Records(60, "Li Fang", 28, "China", "Shanghai", "Outpatient"),
                new Records(61, "Chen Xia", 39, "China", "Shanghai", "Admitted"),
                new Records(62, "Yang Wei", 24, "China", "Shanghai", "Outpatient"),
                new Records(63, "Zhu Xin", 35, "China", "Shanghai", "Admitted"),
                new Records(64, "Liu Jing", 40, "China", "Shanghai", "Outpatient"),
                new Records(65, "Zhang Wei", 30, "China", "Shanghai", "Admitted"),
                new Records(66, "Wang Hong", 25, "China", "Shanghai", "Outpatient"),
                new Records(67, "Li Ming", 40, "China", "Shanghai", "Dead"),
                new Records(68, "Liu Yan", 35, "China", "Shanghai", "Admitted"),
                new Records(69, "Chen Xiaojun", 28, "China", "Shanghai", "Outpatient"),
                new Records(70, "Yang Lei", 45, "China", "Shanghai", "Admitted"),
                new Records(71, "Zhao Xin", 32, "China", "Shanghai", "Outpatient"),
                new Records(72, "Huang Lin", 27, "China", "Shanghai", "Admitted"),
                new Records(73, "Wu Qiang", 38, "China", "Shanghai", "Outpatient"),
                new Records(74, "Zhou Jing", 31, "China", "Shanghai", "Dead"),
                new Records(75, "Xu Fang", 29, "China", "Shanghai", "Admitted"),
                new Records(76, "Sun Jing", 34, "China", "Shanghai", "Outpatient"),
                new Records(77, "He Ying", 26, "China", "Shanghai", "Admitted"),
                new Records(78, "Gao Peng", 33, "China", "Shanghai", "Outpatient"),
                new Records(79, "Zhu Wei", 42, "China", "Shanghai", "Admitted"),
                new Records(80, "Li Na", 37, "China", "Shanghai", "Outpatient"),
                new Records(81, "Xie Jun", 39, "China", "Shanghai", "Admitted"),
                new Records(82, "Tang Xiao", 24, "China", "Shanghai", "Outpatient"),
                new Records(83, "Cheng Fang", 36, "China", "Shanghai", "Admitted"),
                new Records(84, "Yu Xin", 28, "China", "Shanghai", "Outpatient"),
                new Records(85, "Wang Jun", 41, "China", "Shanghai", "Admitted"),
                new Records(86, "Chen Wei", 26, "China", "Shanghai", "Outpatient"),
                new Records(87, "Zhang Xiao", 29, "China", "Shanghai", "Admitted"),
                new Records(88, "Liu Fang", 32, "China", "Shanghai", "Outpatient"),
                new Records(89, "Hu Lei", 35, "China", "Shanghai", "Admitted"),
                new Records(90, "Xu Xiao", 27, "China", "Shanghai", "Outpatient"),
                new Records(91, "Wu Jing", 30, "China", "Shanghai", "Admitted"),
                new Records(92, "Zheng Wei", 38, "China", "Shanghai", "Outpatient"),
                new Records(93, "Wang Jing", 33, "China", "Shanghai", "Admitted"),
                new Records(94, "Li Hong", 24, "China", "Shanghai", "Outpatient"),
                new Records(95, "Chen Lei", 36, "China", "Shanghai", "Admitted"),
                new Records(96, "Yang Xiao", 28, "China", "Shanghai", "Outpatient"),
                new Records(97, "Zhu Jun", 41, "China", "Shanghai", "Admitted"),
                new Records(98, "Liu Jing", 26, "China", "Shanghai", "Outpatient"),
                new Records(99, "Sun Wei", 39, "China", "Shanghai", "Admitted"),
                new Records(100, "Gao Fang", 32, "China", "Shanghai", "Outpatient"),
                new Records(101, "Zhao Xiaojie", 30, "China", "Shanghai", "Admitted"),
                new Records(102, "Wu Fang", 28, "China", "Shanghai", "Outpatient"),
                new Records(103, "Zhou Lei", 41, "China", "Shanghai", "Admitted"),
                new Records(104, "Xu Min", 26, "China", "Shanghai", "Outpatient"),
                new Records(105, "Huang Fang", 36, "China", "Shanghai", "Admitted"),
                new Records(106, "Yu Jing", 29, "China", "Shanghai", "Outpatient"),
                new Records(107, "Wang Lei", 39, "China", "Shanghai", "Admitted"),
                new Records(108, "Li Xia", 25, "China", "Shanghai", "Outpatient"),
                new Records(109, "Zhang Hong", 36, "China", "Shanghai", "Admitted"),
                new Records(110, "Liu Xin", 28, "China", "Shanghai", "Outpatient"),
                new Records(111, "Chen Wei", 33, "China", "Shanghai", "Admitted"),
                new Records(112, "Xie Ling", 42, "China", "Shanghai", "Outpatient"),
                new Records(113, "Tang Wei", 29, "China", "Shanghai", "Admitted"),
                new Records(114, "Yu Min", 34, "China", "Shanghai", "Outpatient"),
                new Records(115, "Wang Fang", 31, "China", "Shanghai", "Admitted"),
                new Records(116, "Cheng Xiao", 26, "China", "Shanghai", "Outpatient"),
                new Records(117, "Zhu Fang", 39, "China", "Shanghai", "Admitted"),
                new Records(118, "Sun Min", 25, "China", "Shanghai", "Outpatient"),
                new Records(119, "Hu Jing", 30, "China", "Shanghai", "Admitted"),
                new Records(120, "Xu Wei", 37, "China", "Shanghai", "Outpatient"),
                new Records(121, "Wu Lei", 41, "China", "Shanghai", "Admitted"),
                new Records(122, "Zheng Hong", 27, "China", "Shanghai", "Outpatient"),
                new Records(123, "Wang Xiao", 36, "China", "Shanghai", "Admitted"),
                new Records(124, "Li Fang", 28, "China", "Shanghai", "Outpatient"),
                new Records(125, "Chen Xia", 39, "China", "Shanghai", "Admitted"),
                new Records(126, "Yang Wei", 24, "China", "Shanghai", "Outpatient"),
                new Records(127, "Zhu Xin", 35, "China", "Shanghai", "Admitted"),
                new Records(128, "Liu Jing", 40, "China", "Shanghai", "Outpatient"),
                new Records(129, "Zhang Wei", 30, "China", "Shanghai", "Admitted"),
                new Records(130, "Wang Hong", 25, "China", "Shanghai", "Outpatient"),
                new Records(131, "Li Ming", 40, "China", "Shanghai", "Dead"),
                new Records(132, "Liu Yan", 35, "China", "Shanghai", "Admitted"),
                new Records(133, "Chen Xiaojun", 28, "China", "Shanghai", "Outpatient"),
                new Records(134, "Yang Lei", 45, "China", "Shanghai", "Admitted"),
                new Records(135, "Zhao Xin", 32, "China", "Shanghai", "Outpatient"),
                new Records(136, "Huang Lin", 27, "China", "Shanghai", "Admitted"),
                new Records(137, "Wu Qiang", 38, "China", "Shanghai", "Outpatient"),
                new Records(138, "Zhou Jing", 31, "China", "Shanghai", "Dead"),
                new Records(139, "Xu Fang", 29, "China", "Shanghai", "Admitted"),
                new Records(140, "Sun Jing", 34, "China", "Shanghai", "Outpatient"),
                new Records(141, "He Ying", 26, "China", "Shanghai", "Admitted"),
                new Records(142, "Gao Peng", 33, "China", "Shanghai", "Outpatient"),
                new Records(143, "Zhu Wei", 42, "China", "Shanghai", "Admitted"),
                new Records(144, "Li Na", 37, "China", "Shanghai", "Outpatient"),
                new Records(145, "Xie Jun", 39, "China", "Shanghai", "Admitted"),
                new Records(146, "Tang Xiao", 24, "China", "Shanghai", "Outpatient"),
                new Records(147, "Cheng Fang", 36, "China", "Shanghai", "Admitted"),
                new Records(148, "Yu Xin", 28, "China", "Shanghai", "Outpatient"),
                new Records(149, "Wang Jun", 41, "China", "Shanghai", "Admitted"),
                new Records(150, "Chen Wei", 26, "China", "Shanghai", "Outpatient"),
                new Records(151, "Zhang Xiao", 29, "China", "Shanghai", "Admitted"),
                new Records(152, "Liu Fang", 32, "China", "Shanghai", "Outpatient"),
                new Records(153, "Hu Lei", 35, "China", "Shanghai", "Admitted"),
                new Records(154, "Xu Xiao", 27, "China", "Shanghai", "Outpatient"),
                new Records(155, "Wu Jing", 30, "China", "Shanghai", "Admitted"),
                new Records(156, "Zheng Wei", 38, "China", "Shanghai", "Outpatient"),
                new Records(157, "Wang Jing", 33, "China", "Shanghai", "Admitted"),
                new Records(158, "Li Hong", 24, "China", "Shanghai", "Outpatient"),
                new Records(159, "Chen Lei", 36, "China", "Shanghai", "Admitted"),
                new Records(160, "Yang Xiao", 28, "China", "Shanghai", "Outpatient"),
                new Records(161, "Zhu Jun", 41, "China", "Shanghai", "Admitted"),
                new Records(162, "Liu Jing", 26, "China", "Shanghai", "Outpatient"),
                new Records(163, "Sun Wei", 39, "China", "Shanghai", "Admitted"),
                new Records(164, "Gao Fang", 32, "China", "Shanghai", "Outpatient")
        };
        Records[] DehliRecords = {
                new Records(1, "Rahul Sharma", 30, "India", "Delhi", "Admitted"),
                new Records(2, "Priya Singh", 25, "India", "Delhi", "Outpatient"),
                new Records(3, "Rakesh Kumar", 40, "India", "Delhi", "Dead"),
                new Records(4, "Sunita Verma", 35, "India", "Delhi", "Admitted"),
                new Records(5, "Anil Gupta", 28, "India", "Delhi", "Outpatient"),
                new Records(6, "Meena Devi", 45, "India", "Delhi", "Admitted"),
                new Records(7, "Rajesh Patel", 32, "India", "Delhi", "Outpatient"),
                new Records(8, "Anita Jain", 27, "India", "Delhi", "Admitted"),
                new Records(9, "Vikram Singh", 38, "India", "Delhi", "Outpatient"),
                new Records(10, "Kiran Sharma", 31, "India", "Delhi", "Dead"),
                new Records(11, "Deepak Gupta", 29, "India", "Delhi", "Admitted"),
                new Records(12, "Pooja Yadav", 34, "India", "Delhi", "Outpatient"),
                new Records(13, "Amit Verma", 26, "India", "Delhi", "Admitted"),
                new Records(14, "Neetu Singh", 33, "India", "Delhi", "Outpatient"),
                new Records(15, "Sanjay Kumar", 42, "India", "Delhi", "Admitted"),
                new Records(16, "Kavita Gupta", 37, "India", "Delhi", "Outpatient"),
                new Records(17, "Arvind Jain", 39, "India", "Delhi", "Admitted"),
                new Records(18, "Shalini Agarwal", 24, "India", "Delhi", "Outpatient"),
                new Records(19, "Vijay Kumar", 36, "India", "Delhi", "Admitted"),
                new Records(20, "Anjali Sharma", 28, "India", "Delhi", "Outpatient"),
                new Records(21, "Rohit Gupta", 41, "India", "Delhi", "Admitted"),
                new Records(22, "Geeta Singh", 26, "India", "Delhi", "Outpatient"),
                new Records(23, "Harish Verma", 29, "India", "Delhi", "Admitted"),
                new Records(24, "Kavita Patel", 32, "India", "Delhi", "Outpatient"),
                new Records(25, "Suresh Kumar", 35, "India", "Delhi", "Admitted"),
                new Records(26, "Priyanka Gupta", 27, "India", "Delhi", "Outpatient"),
                new Records(27, "Rajeev Jain", 30, "India", "Delhi", "Admitted"),
                new Records(28, "Kirti Sharma", 38, "India", "Delhi", "Outpatient"),
                new Records(29, "Anuj Singh", 33, "India", "Delhi", "Admitted"),
                new Records(30, "Sarita Verma", 24, "India", "Delhi", "Outpatient"),
                new Records(31, "Mukesh Gupta", 36, "India", "Delhi", "Admitted"),
                new Records(32, "Neha Singh", 29, "India", "Delhi", "Outpatient"),
                new Records(33, "Alok Jain", 42, "India", "Delhi", "Admitted"),
                new Records(34, "Anita Yadav", 37, "India", "Delhi", "Outpatient"),
                new Records(35, "Sachin Kumar", 39, "India", "Delhi", "Admitted"),
                new Records(36, "Rekha Gupta", 24, "India", "Delhi", "Outpatient"),
                new Records(37, "Arjun Singh", 36, "India", "Delhi", "Admitted"),
                new Records(38, "Manju Verma", 28, "India", "Delhi", "Outpatient"),
                new Records(39, "Vishal Sharma", 41, "India", "Delhi", "Admitted"),
                new Records(40, "Komal Gupta", 26, "India", "Delhi", "Outpatient"),
                new Records(41, "Rajiv Singh", 36, "India", "Delhi", "Admitted"),
                new Records(42, "Suman Verma", 29, "India", "Delhi", "Outpatient"),
                new Records(43, "Avinash Jain", 39, "India", "Delhi", "Admitted"),
                new Records(44, "Meenakshi Patel", 25, "India", "Delhi", "Outpatient"),
                new Records(45, "Vivek Kumar", 36, "India", "Delhi", "Admitted"),
                new Records(46, "Seema Gupta", 28, "India", "Delhi", "Outpatient"),
                new Records(47, "Vikas Singh", 33, "India", "Delhi", "Admitted"),
                new Records(48, "Poonam Verma", 42, "India", "Delhi", "Outpatient"),
                new Records(49, "Pradeep Sharma", 29, "India", "Delhi", "Admitted"),
                new Records(50, "Nisha Singh", 34, "India", "Delhi", "Outpatient"),
                new Records(51, "Anand Gupta", 31, "India", "Delhi", "Admitted"),
                new Records(52, "Manisha Jain", 26, "India", "Delhi", "Outpatient"),
                new Records(53, "Rajesh Verma", 39, "India", "Delhi", "Admitted"),
                new Records(54, "Kavita Singh", 25, "India", "Delhi", "Outpatient"),
                new Records(55, "Sumit Kumar", 30, "India", "Delhi", "Admitted"),
                new Records(56, "Sangeeta Gupta", 37, "India", "Delhi", "Outpatient"),
                new Records(57, "Raj Kumar", 41, "India", "Delhi", "Admitted"),
                new Records(58, "Neelam Verma", 27, "India", "Delhi", "Outpatient"),
                new Records(59, "Sunil Sharma", 36, "India", "Delhi", "Admitted"),
                new Records(60, "Kumari Singh", 28, "India", "Delhi", "Outpatient"),
                new Records(61, "Pankaj Gupta", 39, "India", "Delhi", "Admitted"),
                new Records(62, "Preeti Jain", 24, "India", "Delhi", "Outpatient"),
                new Records(63, "Ajay Singh", 35, "India", "Delhi", "Admitted"),
                new Records(64, "Anju Verma", 40, "India", "Delhi", "Outpatient"),
                new Records(65, "Praveen Sharma", 30, "India", "Delhi", "Admitted"),
                new Records(66, "Kusum Gupta", 25, "India", "Delhi", "Outpatient"),
                new Records(67, "Ashok Singh", 40, "India", "Delhi", "Admitted"),
                new Records(68, "Kiran Verma", 35, "India", "Delhi", "Outpatient"),
                new Records(69, "Rajni Sharma", 28, "India", "Delhi", "Admitted"),
                new Records(70, "Rahul Gupta", 33, "India", "Delhi", "Outpatient"),
                new Records(71, "Mamta Singh", 42, "India", "Delhi", "Admitted"),
                new Records(72, "Mohit Verma", 29, "India", "Delhi", "Outpatient"),
                new Records(73, "Rashmi Jain", 36, "India", "Delhi", "Admitted"),
                new Records(74, "Sumit Kumar", 24, "India", "Delhi", "Outpatient"),
                new Records(75, "Shweta Gupta", 37, "India", "Delhi", "Admitted"),
                new Records(76, "Sandeep Singh", 26, "India", "Delhi", "Outpatient"),
                new Records(77, "Neetu Verma", 39, "India", "Delhi", "Admitted"),
                new Records(78, "Rajesh Sharma", 25, "India", "Delhi", "Outpatient"),
                new Records(79, "Namita Singh", 31, "India", "Delhi", "Admitted"),
                new Records(80, "Sanjay Gupta", 38, "India", "Delhi", "Outpatient"),
                new Records(81, "Priya Sharma", 33, "India", "Delhi", "Admitted"),
                new Records(82, "Amit Kumar", 41, "India", "Delhi", "Outpatient"),
                new Records(83, "Nisha Verma", 26, "India", "Delhi", "Admitted"),
                new Records(84, "Prakash Singh", 35, "India", "Delhi", "Outpatient"),
                new Records(85, "Neelam Gupta", 40, "India", "Delhi", "Admitted"),
                new Records(86, "Vijay Verma", 27, "India", "Delhi", "Outpatient"),
                new Records(87, "Seema Singh", 34, "India", "Delhi", "Admitted"),
                new Records(88, "Rahul Verma", 29, "India", "Delhi", "Outpatient"),
                new Records(89, "Kirti Singh", 38, "India", "Delhi", "Admitted"),
                new Records(90, "Vikas Verma", 31, "India", "Delhi", "Outpatient"),
                new Records(91, "Komal Singh", 42, "India", "Delhi", "Admitted"),
                new Records(92, "Vinod Verma", 24, "India", "Delhi", "Outpatient"),
                new Records(93, "Rani Sharma", 36, "India", "Delhi", "Admitted"),
                new Records(94, "Ravi Gupta", 28, "India", "Delhi", "Outpatient"),
                new Records(95, "Pooja Verma", 39, "India", "Delhi", "Admitted"),
                new Records(96, "Alok Singh", 25, "India", "Delhi", "Outpatient"),
                new Records(97, "Anita Verma", 30, "India", "Delhi", "Admitted"),
                new Records(98, "Ashish Singh", 37, "India", "Delhi", "Outpatient"),
                new Records(99, "Sunita Gupta", 41, "India", "Delhi", "Admitted"),
                new Records(100, "Arvind Verma", 26, "India", "Delhi", "Outpatient"),
                new Records(101, "Sarita Singh", 35, "India", "Delhi", "Admitted"),
                new Records(102, "Sumit Verma", 28, "India", "Delhi", "Outpatient"),
                new Records(103, "Kusum Singh", 40, "India", "Delhi", "Admitted"),
                new Records(104, "Ajay Verma", 27, "India", "Delhi", "Outpatient"),
                new Records(105, "Rajni Singh", 36, "India", "Delhi", "Admitted"),
                new Records(106, "Rahul Verma", 29, "India", "Delhi", "Outpatient"),
                new Records(107, "Rohini Singh", 38, "India", "Delhi", "Admitted"),
                new Records(108, "Vijay Singh", 31, "India", "Delhi", "Outpatient"),
                new Records(109, "Pooja Verma", 42, "India", "Delhi", "Admitted"),
                new Records(110, "Sunil Singh", 24, "India", "Delhi", "Outpatient"),
                new Records(111, "Rashmi Verma", 36, "India", "Delhi", "Admitted"),
                new Records(112, "Sandeep Singh", 28, "India", "Delhi", "Outpatient"),
                new Records(113, "Neelam Singh", 39, "India", "Delhi", "Admitted"),
                new Records(114, "Sanjay Verma", 25, "India", "Delhi", "Outpatient"),
                new Records(115, "Anjali Singh", 30, "India", "Delhi", "Admitted"),
                new Records(116, "Vivek Verma", 37, "India", "Delhi", "Outpatient"),
                new Records(117, "Rekha Singh", 41, "India", "Delhi", "Admitted"),
                new Records(118, "Ankit Verma", 26, "India", "Delhi", "Outpatient"),
                new Records(119, "Priya Singh", 35, "India", "Delhi", "Admitted"),
                new Records(120, "Pradeep Verma", 28, "India", "Delhi", "Outpatient"),
                new Records(121, "Nisha Singh", 40, "India", "Delhi", "Admitted"),
                new Records(122, "Pankaj Verma", 27, "India", "Delhi", "Outpatient"),
                new Records(123, "Rohini Singh", 36, "India", "Delhi", "Admitted"),
                new Records(124, "Amit Verma", 29, "India", "Delhi", "Outpatient"),
                new Records(125, "Kusum Verma", 38, "India", "Delhi", "Admitted"),
                new Records(126, "Praveen Singh", 31, "India", "Delhi", "Outpatient"),
                new Records(127, "Seema Verma", 42, "India", "Delhi", "Admitted"),
                new Records(128, "Vinod Singh", 24, "India", "Delhi", "Outpatient"),
                new Records(129, "Sunil Verma", 36, "India", "Delhi", "Admitted"),
                new Records(130, "Kumari Singh", 28, "India", "Delhi", "Outpatient"),
                new Records(131, "Pradeep Verma", 39, "India", "Delhi", "Admitted"),
                new Records(132, "Sangeeta Singh", 25, "India", "Delhi", "Outpatient"),
                new Records(133, "Raj Kumar", 30, "India", "Delhi", "Admitted"),
                new Records(134, "Rekha Verma", 37, "India", "Delhi", "Outpatient"),
                new Records(135, "Vivek Singh", 41, "India", "Delhi", "Admitted"),
                new Records(136, "Manju Verma", 26, "India", "Delhi", "Outpatient"),
                new Records(137, "Sunil Kumar", 35, "India", "Delhi", "Admitted"),
                new Records(138, "Meena Singh", 40, "India", "Delhi", "Outpatient"),
                new Records(139, "Rakesh Verma", 27, "India", "Delhi", "Admitted"),
                new Records(140, "Neetu Singh", 36, "India", "Delhi", "Outpatient"),
                new Records(141, "Sanjay Verma", 29, "India", "Delhi", "Admitted"),
                new Records(142, "Anjali Singh", 38, "India", "Delhi", "Outpatient"),
                new Records(143, "Vikas Verma", 31, "India", "Delhi", "Admitted"),
                new Records(144, "Neelam Singh", 42, "India", "Delhi", "Outpatient"),
                new Records(145, "Amit Kumar", 26, "India", "Delhi", "Admitted"),
                new Records(146, "Kavita Verma", 33, "India", "Delhi", "Outpatient"),
                new Records(147, "Sumit Singh", 39, "India", "Delhi", "Admitted"),
                new Records(148, "Anita Verma", 24, "India", "Delhi", "Outpatient"),
                new Records(149, "Ashish Kumar", 36, "India", "Delhi", "Admitted"),
                new Records(150, "Sunita Singh", 29, "India", "Delhi", "Outpatient"),
                new Records(151, "Arvind Verma", 37, "India", "Delhi", "Admitted"),
                new Records(152, "Pooja Singh", 41, "India", "Delhi", "Outpatient"),
                new Records(153, "Anil Verma", 26, "India", "Delhi", "Admitted"),
                new Records(154, "Sarita Singh", 35, "India", "Delhi", "Outpatient"),
                new Records(155, "Ashok Verma", 40, "India", "Delhi", "Admitted"),
                new Records(156, "Neetu Verma", 27, "India", "Delhi", "Outpatient"),
                new Records(157, "Rohit Kumar", 36, "India", "Delhi", "Admitted"),
                new Records(158, "Anita Singh", 28, "India", "Delhi", "Outpatient")
        };
        System.out.println("a)");
        System.out.println("New York");
        Computation(NewyorkRecords);
        System.out.println("London");
        Computation(londonRecords);
        System.out.println("Lagos");
        Computation(LagosRecords);
        System.out.println("Johannesburg");
        Computation(JohannesburgRecords);
        System.out.println("Windhoek");
        Computation(WindhoekRecords);
        System.out.println("Shanghai");
        Computation(ShanghaiRecords);
        System.out.println("Dehli");
        Computation(DehliRecords);

        System.out.println("b)");
        Process[] proc = { new Process("New York", 150, 0),
                new Process("London", 100, 20),
                new Process("Lagos", 120, 25),
                new Process("Johannesburg", 88, 30),
                new Process("Windhoek", 15, 35),
                new Process("Shanghai", 164, 50),
                new Process("Delhi", 158, 55)};

        avgTime(proc, proc.length);
    }

}




